### ISSUE TITLE
Flickr2piwigo unusable

### ISSUE THREAD

**Issue by agoldin** [mistic100/Flickr2Piwigo#50] opened 2019-11-21 04:55 UTC
Fresh install, latest version. Followed instructions, got API keys. Managed to login to Flickr, got list of my albums allright. However no matter which album I choose I can not see a  single image in them and can not import anything. In the upper part of the import window I can see the traceback:

Notice: Undefined index: photoset in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 189

Deprecated: Function create_function() is deprecated in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 199

Warning: Invalid argument supplied for foreach() in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 203

Warning: array_slice() expects parameter 1 to be array, null given in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 221

Deprecated: Function create_function() is deprecated in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 222

Warning: array_map(): Expected parameter 2 to be an array, null given in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 222

Warning: Invalid argument supplied for foreach() in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 224

Warning: count(): Parameter must be an array or an object that implements Countable in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 233

Warning: count(): Parameter must be an array or an object that implements Countable in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 234

Warning: count(): Parameter must be an array or an object that implements Countable in /config/www/gallery/plugins/flickr2piwigo/admin/import.php on line 252

In "selection" : 

Selection
No photo in the current set.

Tried to reinstall a few times, no luck. 

Am I missing something completely obvious??

**Comment by samwilson** [comment] 2019-11-21 06:13
What version of PHP are you running?

Does the import-all function have the same errors?

**Comment by agoldin** [comment] 2019-11-21 14:09
php --version
PHP 7.3.11 (cli) (built: Oct 26 2019 06:24:35) ( NTS )

I am running linuxserver docker version:  https://github.com/linuxserver/docker-piwigo

Should I try asking them what is going on? 

Import-all seems to be working (I just started it, there are about 400 pictures, so I have to wait to see if it completes OK).

**Comment by agoldin** [comment] 2019-11-22 02:58
Yes, Import-all seems to be working. There are some other strange errors, but importing all albums is possible (by admin user anyway). This makes my complain much less urgent :-)

**Comment by samwilson** [comment] 2019-11-22 03:08
Ah, that's good to hear. I guess most people probably use this plugin to migrate off Flickr, which is why the errors in the per-album import process haven't been flagged until now. Still, I'll try to find some time to look at it and get it working.

**Comment by benjaminchodroff** [comment] 2019-12-18 09:24
I have contributed a patch which should fix this issue - I hit the same. 
https://github.com/samwilson/phpflickr/pull/26

**Comment by milescrawford** [comment] 2020-03-27 20:16
I'm hitting a similar issue, and do not want to import 100% of my flickr account :/

<img width="999" alt="Screenshot 2020-03-27 13 14 17" src="https://user-images.githubusercontent.com/11055723/77796754-1b2d1500-702d-11ea-89c0-3c8beccd6515.png">

**Comment by benjaminchodroff** [comment] 2020-03-30 10:29
Please close this issue? @samwilson 

@milescrawford I would suggest opening a new issue and including your log file, confirm you are on latest version, and steps taken to reproduce the issue. I just tested my local instance... couldn't reproduce the issue. Sorry!

**Comment by samwilson** [comment] 2020-04-01 00:47
Thanks @benjaminchodroff.

@milescrawford yes, this sounds like it might be a slightly different issue.

**Closed by samwilson** 2020-04-01 00:47 UTC
